spring.application.name=api-gateway

server.port=8080

jwt.secret=j=${SECRET_TOKEN:jtufud56j8f75dsg6jgi6u7g67558j9hj0phh0fu5fjhytthgygfyyyrjgutiokigjuhfgrg}

spring.data.redis.port=6379
spring.data.redis.host=${REDIS_HOST:localhost}

eureka.client.service-url.defaultZone=http://${SERVICE_REGISTRY_HOST:localhost}:8761/register/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=payment-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/payment-service/payment/**,/payment/**

# --- Filter 0: CIRCUIT BREAKER (Outer) ---
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.name=paymentCircuit
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.fallbackUri=forward:/fallback/payment

# --- Filter 1: RETRY (Inner) ---
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=Retry
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.name=paymentRetry
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.retries=3
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.methods=GET
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.exceptions=java.io.IOException,org.springframework.cloud.gateway.support.NotFoundException
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.backoff.firstBackoff=100ms

#-------Filter 2: Rate Limiter-----------
spring.cloud.gateway.server.webflux.routes[0].filters[2].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[0].filters[2].args.key-resolver=#{@ipKeyResolver}

# =========================================================
# CIRCUIT BREAKER (mapped to 'paymentCircuit')
# =========================================================
resilience4j.circuitbreaker.instances.paymentCircuit.register-health-indicator=true
resilience4j.circuitbreaker.instances.paymentCircuit.sliding-window-size=10
resilience4j.circuitbreaker.instances.paymentCircuit.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.paymentCircuit.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentCircuit.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentCircuit.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.paymentCircuit.automatic-transition-from-open-to-half-open-enabled=true

spring.cloud.gateway.server.webflux.routes[1].id=inventory-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventory-service/inventory/**,/inventory/**

# --- Filter 0: CIRCUIT BREAKER (Outer) ---
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.name=inventoryCircuit
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.fallbackUri=forward:/fallback/inventory

# --- Filter 1: RETRY (Inner) ---
spring.cloud.gateway.server.webflux.routes[1].filters[1].name=Retry
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.name=inventoryRetry
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.retries=3
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.methods=GET
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.exceptions=java.io.IOException,org.springframework.cloud.gateway.support.NotFoundException
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.backoff.firstBackoff=100ms

#-------Filter 2: Rate Limiter-----------
spring.cloud.gateway.server.webflux.routes[1].filters[2].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[1].filters[2].args.key-resolver=#{@ipKeyResolver}


# =========================================================
# CIRCUIT BREAKER (mapped to 'inventoryCircuit')
# =========================================================
resilience4j.circuitbreaker.instances.inventoryCircuit.register-health-indicator=true
resilience4j.circuitbreaker.instances.inventoryCircuit.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventoryCircuit.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.inventoryCircuit.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.inventoryCircuit.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.inventoryCircuit.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.inventoryCircuit.automatic-transition-from-open-to-half-open-enabled=true

spring.cloud.gateway.server.webflux.routes[2].id=sentinel-orchestrator-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://SENTINEL-ORCHESTRATOR-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/sentinel-orchestrator-service/workflow/**,/workflow/**

# --- Filter 0: CIRCUIT BREAKER (Outer) ---
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.name=sentinelCircuit
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.fallbackUri=forward:/fallback/sentinel

# --- Filter 1: RETRY (Inner) ---
spring.cloud.gateway.server.webflux.routes[2].filters[1].name=Retry
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.name=sentinelRetry
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.retries=3
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.methods=GET
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.exceptions=java.io.IOException,org.springframework.cloud.gateway.support.NotFoundException
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.backoff.firstBackoff=100ms

#-------Filter 2: Rate Limiter-----------
spring.cloud.gateway.server.webflux.routes[2].filters[2].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[2].filters[2].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.server.webflux.routes[2].filters[2].args.redis-rate-limiter.burstCapacity=10
spring.cloud.gateway.server.webflux.routes[2].filters[2].args.key-resolver=#{@ipKeyResolver}

# =========================================================
# CIRCUIT BREAKER (mapped to 'sentinelCircuit')
# =========================================================
resilience4j.circuitbreaker.instances.sentinelCircuit.register-health-indicator=true
resilience4j.circuitbreaker.instances.sentinelCircuit.sliding-window-size=10
resilience4j.circuitbreaker.instances.sentinelCircuit.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.sentinelCircuit.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.sentinelCircuit.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.sentinelCircuit.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.sentinelCircuit.automatic-transition-from-open-to-half-open-enabled=true